$(document).ready(function(){
  $("#list1").on("mouseover",function(){
    $(this).addClass("class1");
  });
  $("#list1").on("mouseout",function(){
    $(this).removeClass("class1");
  });
  $("#list2").on("mouseover",function(){
    $(this).addClass("class1");
  });
  $("#list2").on("mouseout",function(){
    $(this).removeClass("class1");
  });
  $("#list3").on("mouseover",function(){
    $(this).addClass("class1");
  });
  $("#list3").on("mouseout",function(){
    $(this).removeClass("class1");
  });
  $("#list4").on("mouseover",function(){
    $(this).addClass("class1");
  });
  $("#list4").on("mouseout",function(){
    $(this).removeClass("class1");
  });
});
